pipeline:
  name: test input set
  identifier: test_input_set
  projectIdentifier: test_adithya
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: fsd
        identifier: fsd
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: fds
                  identifier: fds
                  type: HarnessApproval
                  timeout: <+input>
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
