pipeline:
  name: demo pipeline
  identifier: demo_pipeline
  projectIdentifier: adithya_test
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: s2
                  identifier: s2
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression update
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
    - stage:
        name: s2
        identifier: s2
        tags: {}
        template:
          templateRef: org.test_org_template
          versionLabel: v1
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: sfd
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
    - stage:
        name: s3
        identifier: s3
        tags: {}
        template:
          templateRef: import_from_non_default2
          versionLabel: v1
          gitBranch: PipelineRemote_1739293842714
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: sdf
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
