pipeline:
  name: pipe-36071-2
  identifier: pipe360712
  projectIdentifier: adithya_test
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: fd
        identifier: fd
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: dsf
                  identifier: dsf
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression dfasdf
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
