pipeline:
  name: pipeline 123
  identifier: pipeline_123
  projectIdentifier: adithya_test
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: vd
        identifier: vd
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: vd
                  identifier: vd
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information sdfg
                      and approve the pipeline progression asdfasdf
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
