pipeline:
  name: pipeline non default branch
  identifier: pipeline_non_default_branch
  projectIdentifier: adithya_test
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: fasd
        identifier: fasd
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: fads
                  identifier: fads
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
