pipeline:
  name: test dry run
  identifier: test_dry_run
  projectIdentifier: adithya_test
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: adsf
        identifier: adsf
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: sfd
                  identifier: sfd
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following informationasdjkcf
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
