pipeline:
  name: aaaabcd1
  identifier: aaaabcd1
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: sdf
        identifier: sdf
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: df
                  identifier: df
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following inform   fation
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
