pipeline:
  name: aaaabcd2
  identifier: aaaabcd2
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: gc
        identifier: gc
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: hgrt
                  identifier: hgrt
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following infor   mtion
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
