pipeline:
  name: aaqwe456
  identifier: aaqwe456
  projectIdentifier: test_bi_dir_sync
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: dsf
        identifier: dsf
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: df
                  identifier: df
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following informa tion
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
