pipeline:
  name: asdf234
  identifier: asdf234
  projectIdentifier: adithya_test
  orgIdentifier: default_1666106363316
  tags: {}
  stages:
    - stage:
        name: dsfg
        identifier: dsfg
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: dfsg
                  identifier: dfsg
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following informa tion
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
