pipeline:
  name: asdfasdfasdf
  identifier: asdfasdfasdf
  projectIdentifier: AmitTest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: scd
        identifier: scd
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: sdc
                  identifier: sdc
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following info
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
