pipeline:
  name: auto creation prod2 test
  identifier: auto_creation_prod2_test
  projectIdentifier: test_adithya
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: df
        identifier: df
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: dsf
                  identifier: dsf
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
