pipeline:
  name: bi dir with ref entity
  identifier: bi_dir_with_ref_entity
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: dfs1
        identifier: d
        tags: {}
        template:
          templateRef: org.asdfasd_stage_gitx
          versionLabel: v1
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: asfswer
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
    - stage:
        name: sdcdfsda
        identifier: sdcdfsda
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: sf
                  identifier: sf
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
