pipeline:
  name: create pipeline reference test
  identifier: create_pipeline_reference_test
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: ds
        identifier: ds
        template:
          templateRef: testStage_template_v2
          versionLabel: vwe
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: dsf
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
