pipeline:
  name: demo pipeline - no template
  identifier: demo_pipeline_no_template
  projectIdentifier: do_not_delete_demo
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: approval
                  identifier: approval
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following info
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: <+input>
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
