pipeline:
  name: execution_test_pipeline_2
  identifier: execution_test_pipeline_2
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        template:
          templateRef: stage_template_execution_test
          versionLabel: v1
