pipeline:
  name: gitx test status page qa
  identifier: gitx_test_status_page_qa
  projectIdentifier: AmitTest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: fd
        identifier: fd
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: sdf
                  identifier: sdf
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following infor  mation
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
