pipeline:
  name: InsertPipeline
  identifier: InsertPipeline
  projectIdentifier: naidusanity
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        tags: {}
        template:
          templateRef: insertStage
          versionLabel: v1.0
          templateInputs:
            type: Custom
            spec:
              execution:
                steps:
                  - insert:
                      identifier: intert1
                      steps: <+input>
