pipeline:
  name: pipeline gitx123123
  identifier: pipeline_gitx123123
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: sdfa
        identifier: sdfa
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: dsaf
                  identifier: dsaf
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following infor
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
