pipeline:
  name: pipelineGitXmaster
  identifier: pipelineGitXmaster
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: adf1
        identifier: adf
        template:
          templateRef: stageDemoMain
          versionLabel: v2
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: as
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
