pipeline:
  name: sdfsdfgsdagsdfgsdg
  identifier: sdfsdfgsdagsdfgsdg
  projectIdentifier: test_adithya
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: dzv
        identifier: dzv
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: dvzf
                  identifier: dvzf
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
