pipeline:
  name: test valiadtion qa yaml
  identifier: test_valiadtion_qa_yaml
  tags: {}
  stages:
    - stage:
        name: sd
        identifier: sd
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: dsf
                  identifier: dsf
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following  
                      and approve the pipeline 
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
  projectIdentifier: AmitTest
  orgIdentifier: default
