pipeline:
  name: test cfdd remoteee
  identifier: test_cfdd_remoteee
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: kj
        identifier: kj
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: kj
                  identifier: kj
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following  tst
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
