pipeline:
  name: test demo pipeline2
  identifier: test_demo_pipeline2
  projectIdentifier: do_not_delete_demo
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        template:
          templateRef: stage_template_demo
          versionLabel: v1
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: stage
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
