pipeline:
  name: test pipeline ref2
  identifier: test_pipeline_ref2
  projectIdentifier: naidusanity
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: dsf
        identifier: dsf
        template:
          templateRef: stage_templtae_v123
          versionLabel: v123
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: s
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
