pipeline:
  name: test new pipeline branch creation
  identifier: test_new_pipeline_branch_creation
  projectIdentifier: naidusanity
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: sfd
        identifier: sfd
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: sdf
                  identifier: sdf
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
                    callbackId: <+input>
        tags: {}
