pipeline:
  name: test trigger
  identifier: test_trigger
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: dsaf
        identifier: dsaf
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: asdf
                  identifier: asdf
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following info12sd
                      and approve the pipeline progression32d
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
