pipeline:
  name: tst pipeline
  identifier: tst_pipeline
  projectIdentifier: Sanity
  orgIdentifier: DB_Devops
  tags: {}
  stages:
    - stage:
        name: vfd
        identifier: vfd
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: fd
                  identifier: fd
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following 
                      and approve the pipeline
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
