pipeline:
  name: create sregfsdfg
  identifier: create_sregfsdfg
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: fdg
        identifier: fdg
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: dgf
                  identifier: dgf
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
