pipeline:
  name: dry-test
  identifier: drytest
  tags: {}
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  stages:
    - stage:
        name: as
        identifier: as
        tags: {}
        template:
          templateRef: stage_gitx_default
          versionLabel: v1
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: asfd
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
