pipeline:
  name: dsfasdfasdfsafasdf
  identifier: dsfasdfasdfsafasdf
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: asd
        identifier: asd
        tags: {}
        template:
          templateRef: stagesdfgsdfasdf
          versionLabel: asdfasdfasdf
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: sdf
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
