pipeline:
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Deployment
        spec:
          deploymentType: CustomDeployment
          customDeploymentRef:
            templateRef: test_deployment
            versionLabel: v1
          service:
            serviceRef: test_3
          execution:
            steps:
              - step:
                  name: Fetch Instances
                  identifier: fetchInstances
                  type: FetchInstanceScript
                  timeout: 10m
                  spec: {}
            rollbackSteps: []
          environment:
            environmentRef: dsaf
            deployToAll: false
            infrastructureDefinitions:
              - identifier: test_infra
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  identifier: fancy_deployments
  name: 'fancy deployments '
