pipeline:
  name: test gitx retry
  identifier: test_gitx_retry
  tags: {}
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  stages:
    - stage:
        name: sdg
        identifier: sdg
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: sdgf
                  identifier: sdgf
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression sdf
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
