pipeline:
  name: testing auto create
  identifier: testing_auto_create
  tags: {}
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  stages:
    - stage:
        name: fdv
        identifier: fdv
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: vdf
                  identifier: vdf
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
  notificationRules:
    - name: test
      identifier: test
      pipelineEvents:
        - type: PipelineStart
        - type: WaitingForUserAction
      notificationMethod:
        type: Slack
        spec:
          userGroups: []
          webhookUrl: https://webhook.site/f5a90daa-7b8a-4fa0-b352-d62a31943a00
      enabled: true
