pipeline:
  name: verify trigger
  identifier: verify_trigger
  tags: {}
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  stages:
    - stage:
        name: asdf
        identifier: asdf
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: fasd
                  identifier: fasd
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information sd
                      and approve the pipeline progression sdf
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
