pipeline:
  name: remote pipeline tags
  identifier: remote_pipeline_tags
  projectIdentifier: AmitTest
  orgIdentifier: default
  tags:
    c: b
  stages:
    - stage:
        name: s
        identifier: s
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: fd
                  identifier: fd
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
