pipeline:
  name: TestShanshankTrigger
  identifier: TestShanshankTrigger
  tags: {}
  projectIdentifier: AmitTest
  orgIdentifier: default
  stages:
    - stage:
        name: s12
        identifier: s12
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo 10
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
  notificationRules:
    - name: n1
      identifier: n1
      pipelineEvents:
        - type: TriggerFailed
        - type: PipelineStart
        - type: PipelineEnd
        - type: PipelineSuccess
        - type: PipelineFailed
      notificationMethod:
        type: Slack
        spec:
          userGroups: []
          webhookUrl: test
      enabled: true
      template:
        versionLabel: v1
        templateRef: AmitTest12
